apiVersion: v1
kind: Service
metadata:
  name: {{ template "tomcat.fullname" . }}
  labels:
{{ include "tomcat.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: {{ include "tomcat.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
